[tool.poetry]
name = "drukarnia-api"
version = "0.1.0"
description = ""
authors = ["Psychotim <balduev.desco@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "3.8.4"
attrdict = "2.0.1"
fake-useragent = "1.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
