from enum import StrEnum


class DrukarniaEndpoints(StrEnum):
    BlockAuthor = "/api/relationships/block/{author_id}"
    BlockTag = "/api/preferences/tags/{tag_id}/block"
    BookmarkArticle = "/api/articles/bookmarks"
    CreateNewSection = GetSections = "/api/articles/bookmarks/lists"
    DeleteSection = "/api/articles/bookmarks/lists/{section_id}"
    UnBookmarkArticle = "/api/articles/{article_id}/bookmarks"
    ChangeUserGeneralInfo = "/api/users"
    ChangeUserEmail = "/api/users/login/email"
    ChangeUserPassword = "/api/users/login/password"
    DeleteComment = "/api/articles/{article_id}/comments/{comment_id}"
    FindArticles = "/api/articles/search"
    FindAuthors = "/api/users/info"
    FindTags = "/api/articles/search/tags"
    GetArticleInfo = "/api/articles/{slug}"
    GetAuthorInfo = "/api/users/profile/{username}"
    GetBlockedAuthors = "/api/relationships/blocked"
    GetCommentReplies = "/api/articles/{article_id}/comments/{comment_id}/replies"
    GetFollowers = "/api/relationships/{author_id}/followers"
    GetFollowings = "/api/relationships/{author_id}/following"
    GetNotifications = "/api/notifications"
    GetReadsHistory = "/api/stats/reads/history"
    GetTagRelatedArticles = "/api/articles/tags/{tag_id}"
    GetTagRelatedAuthors = "/api/users/tags/{tag_id}/related"
    GetTagRelatedTags = "/api/articles/tags/{tag_id}/related"
    GetTag = "/api/articles/tags/{tag_slug}"
    LikeArticle = "/api/articles/{article_id}/like"
    LikeComment = "/api/articles/{article_id}/comments/{comment_id}/likes"
    AuthorLogin = "/api/users/login"
    PostComment = "/api/articles/{article_id}/comments"
    ReplyToComment = "/api/articles/{article_id}/comments/{comment_id}/replies"
    SubscribeToAuthor = "/api/relationships/subscribe/{author_id}"
    SubscribeToTag = "/api/preferences/tags/{tag_id}"
