from enum import StrEnum


class DrukarniaEndpoints(StrEnum):
    BlockAuthor: str = "/api/relationships/block/{author_id}"
    BlockTag: str = "/api/preferences/tags/{tag_id}/block"
    BookmarkArticle: str = "/api/articles/bookmarks"
    CreateNewSection: str = "/api/articles/bookmarks/lists"
    GetSections: str = CreateNewSection
    DeleteSection: str = "/api/articles/bookmarks/lists/{section_id}"
    UnBookmarkArticle: str = "/api/articles/{article_id}/bookmarks"
    ChangeUserGeneralInfo: str = "/api/users"
    ChangeUserEmail: str = "/api/users/login/email"
    ChangeUserPassword: str = "/api/users/login/password"
    DeleteComment: str = "/api/articles/{article_id}/comments/{comment_id}"
    FindArticles: str = "/api/articles/search"
    FindAuthors: str = "/api/users/info"
    FindTags: str = "/api/articles/search/tags"
    GetArticleInfo: str = "/api/articles/{slug}"
    GetAuthorInfo: str = "/api/users/profile/{username}"
    GetBlockedAuthors: str = "/api/relationships/blocked"
    GetCommentReplies: str = "/api/articles/{article_id}/comments/{comment_id}/replies"
    GetFollowers: str = "/api/relationships/{author_id}/followers"
    GetFollowings: str = "/api/relationships/{author_id}/following"
    GetNotifications: str = "/api/notifications"
    GetReadsHistory: str = "/api/stats/reads/history"
    GetTagRelatedArticles: str = "/api/articles/tags/{tag_id}"
    GetTagRelatedAuthors: str = "/api/users/tags/{tag_id}/related"
    GetTagRelatedTags: str = "/api/articles/tags/{tag_id}/related"
    GetTag: str = "/api/articles/tags/{tag_slug}"
    LikeArticle: str = "/api/articles/{article_id}/like"
    LikeComment: str = "/api/articles/{article_id}/comments/{comment_id}/likes"
    AuthorLogin: str = "/api/users/login"
    PostComment: str = "/api/articles/{article_id}/comments"
    ReplyToComment: str = "/api/articles/{article_id}/comments/{comment_id}/replies"
    SubscribeToAuthor: str = "/api/relationships/subscribe/{author_id}"
    SubscribeToTag: str = "/api/preferences/tags/{tag_id}"
