from drukarnia_api.models.author.author import AuthorModel
from drukarnia_api.models.author.article_author import ArticleAuthorModel
from drukarnia_api.models.author.author_card import AuthorCardModel
from drukarnia_api.models.author.comment_author import CommentAuthorModel
from drukarnia_api.models.author.bookmark_article import BookmarkArticleAuthorModel
from drukarnia_api.models.author.search_result import SearchResultedAuthorModel
from drukarnia_api.models.author.tag_related import TagRelatedAuthorsModel